version: '3.7'
services:
  web:
    # Where find Dockerfile
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/my_project
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=employee_devices_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=employee_devices

volumes:
  postgres_data:

