# Generated by Django 3.1.2 on 2020-10-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('field_1', models.CharField(max_length=255)),
            ],
        ),
    ]
