# Generated by Django 3.1.2 on 2020-10-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0002_auto_20201002_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_1',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
