# Generated by Django 3.1.2 on 2020-10-02 22:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('position', models.IntegerField(choices=[(3, 'Senior'), (1, 'Junior'), (2, 'Developer')], default=1)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('avatar', models.ImageField(null=True, upload_to='')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(3, 'PC'), (2, 'Headphones'), (1, 'Laptop'), (4, 'Teapot')], default=1)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('free', models.BooleanField(default=True)),
                ('current_user', models.ForeignKey(default=None, on_delete=models.SET('do_device_free'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
