# Generated by Django 3.1.2 on 2020-10-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.IntegerField(choices=[(3, 'PC'), (4, 'Teapot'), (1, 'Laptop'), (2, 'Headphones')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(3, 'Senior'), (2, 'Developer'), (1, 'Junior')], default=1),
        ),
    ]
