# Generated by Django 3.1.2 on 2020-10-07 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20201007_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_user',
            field=models.CharField(default=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL), max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.IntegerField(choices=[(3, 'PC'), (4, 'Teapot'), (1, 'Laptop'), (2, 'Headphones')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(4, 'Lead'), (1, 'Junior'), (3, 'Senior'), (2, 'Middle')], default=1),
        ),
    ]
