# Generated by Django 3.1.2 on 2020-10-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20201003_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.IntegerField(choices=[(4, 'Teapot'), (3, 'PC'), (2, 'Headphones'), (1, 'Laptop')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(2, 'Developer'), (1, 'Junior'), (3, 'Senior')], default=1),
        ),
    ]
