# Generated by Django 3.1.2 on 2020-10-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20201003_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.IntegerField(choices=[(2, 'Headphones'), (1, 'Laptop'), (4, 'Teapot'), (3, 'PC')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(3, 'Senior'), (1, 'Junior'), (2, 'Developer')], default=1),
        ),
    ]
