# Generated by Django 3.1.2 on 2020-10-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20201007_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.IntegerField(choices=[(4, 'Teapot'), (1, 'Laptop'), (3, 'PC'), (2, 'Headphones')], default=1),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_user',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(1, 'Junior'), (3, 'Senior'), (4, 'Lead'), (2, 'Middle')], default=1),
        ),
    ]
