# Generated by Django 3.1.2 on 2020-10-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20201003_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.IntegerField(choices=[(1, 'Laptop'), (4, 'Teapot'), (2, 'Headphones'), (3, 'PC')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(2, 'Developer'), (1, 'Junior'), (3, 'Senior')], default=1),
        ),
    ]
