# Generated by Django 3.1.2 on 2020-10-03 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20201003_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.IntegerField(choices=[(2, 'Headphones'), (3, 'PC'), (4, 'Teapot'), (1, 'Laptop')], default=1),
        ),
        migrations.AlterField(
            model_name='device',
            name='current_user',
            field=models.ForeignKey(default=None, null=True, on_delete=models.SET('do_device_free'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(1, 'Junior'), (3, 'Senior'), (2, 'Developer')], default=1),
        ),
    ]
