# Generated by Django 3.1.2 on 2020-10-03 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20201003_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='free',
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.IntegerField(choices=[(4, 'Teapot'), (3, 'PC'), (1, 'Laptop'), (2, 'Headphones')], default=1),
        ),
        migrations.AlterField(
            model_name='device',
            name='current_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(3, 'Senior'), (2, 'Developer'), (1, 'Junior')], default=1),
        ),
    ]
