# Generated by Django 3.1.2 on 2020-10-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20201003_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.IntegerField(choices=[(1, 'Laptop'), (2, 'Headphones'), (3, 'PC'), (4, 'Teapot')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(2, 'Middle'), (3, 'Senior'), (1, 'Junior'), (4, 'Lead')], default=1),
        ),
    ]
