# Generated by Django 3.1.2 on 2020-10-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20201005_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.IntegerField(choices=[(4, 'Teapot'), (3, 'PC'), (2, 'Headphones'), (1, 'Laptop')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(4, 'Lead'), (2, 'Middle'), (3, 'Senior'), (1, 'Junior')], default=1),
        ),
    ]
