# Generated by Django 3.1.2 on 2020-10-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20201005_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.IntegerField(choices=[(3, 'PC'), (2, 'Headphones'), (1, 'Laptop'), (4, 'Teapot')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(4, 'Lead'), (1, 'Junior'), (2, 'Middle'), (3, 'Senior')], default=1),
        ),
    ]
