# Generated by Django 3.1.2 on 2020-10-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20201005_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.IntegerField(choices=[(2, 'Headphones'), (4, 'Teapot'), (1, 'Laptop'), (3, 'PC')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(1, 'Junior'), (3, 'Senior'), (2, 'Middle'), (4, 'Lead')], default=1),
        ),
    ]
