# Generated by Django 3.1.2 on 2020-10-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_auto_20201006_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.IntegerField(choices=[(3, 'PC'), (1, 'Laptop'), (4, 'Teapot'), (2, 'Headphones')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(1, 'Junior'), (4, 'Lead'), (3, 'Senior'), (2, 'Middle')], default=1),
        ),
    ]
