# Generated by Django 3.1.2 on 2020-10-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20201006_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.IntegerField(choices=[(4, 'Teapot'), (2, 'Headphones'), (1, 'Laptop'), (3, 'PC')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(2, 'Middle'), (3, 'Senior'), (4, 'Lead'), (1, 'Junior')], default=1),
        ),
    ]
