# Generated by Django 3.1.2 on 2020-10-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_auto_20201006_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.IntegerField(choices=[(4, 'Teapot'), (1, 'Laptop'), (2, 'Headphones'), (3, 'PC')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(1, 'Junior'), (2, 'Middle'), (3, 'Senior'), (4, 'Lead')], default=1),
        ),
    ]
